---
- name: Disable services
  service:
    name: postfix
    state: stopped
    enabled: "no"
  ignore_errors: "yes"

- block:
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      with_items: []

    - name: Remove packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - postfix
  when: erase == True
