---
- include_tasks: "{{ sf_tasks_dir }}/create_user.yml user_name=zookeeper"

- name: Setup zoo.cfg
  template:
    src: zoo.cfg.j2
    dest: /etc/zookeeper/zoo.cfg
    mode: 0644
  register: _zookeeper_cfg

- name: Restart zookeeper if needed
  service:
    name: zookeeper
    state: restarted
  when: _zookeeper_cfg is changed

- name: Start and enable the service
  service:
    name: zookeeper
    state: started
    enabled: "yes"
