---
- name: "Install managesf venv"
  command: chdir=/usr/src/managesf {{ item }}
  with_items:
    - virtualenv --system-site-packages /var/www/managesf
    - /var/www/managesf/bin/pip install --upgrade 'pbr' 'pip'
    - sed -i 's/^paramiko.*/paramiko<2/' requirements.txt
    - /var/www/managesf/bin/pip install -rrequirements.txt
    - /var/www/managesf/bin/python setup.py install
