---
- name: Disable services
  service:
    name: jenkins
    state: stopped
    enabled: "no"

- block:
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/jenkins
        - /etc/jenkins_jobs
        - "/etc/yum.repos.d/{{ jenkins_repo_name }}.repo"

    - name: Remove packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - jenkins
        - python2-jenkins-job-builder
  when: erase == True
