- block:
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/cauth
        - /etc/httpd/conf.d/cauth.site
        - /var/lib/cauth/keys/privkey.pem
        - /var/log/cauth

    - name: Remove packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - python2-cauth
  when: erase == True
